### ISSUE TITLE
Wallpaper ,screenshot and waybar

### ISSUE THREAD

**Issue by kamaterasu** [flick0/dotfiles#10]
Everytime it boots no wallpaper always blank also it takes screen shot
And waybar clock is wrong and fish is default terminal
Any ideas to fix it

**Comment by flick0** [comment]
fixed the wallpaper in [`234d098`](https://github.com/flick0/dotfiles/commit/234d0984e9dbd54989b983344b91decb568f3b27)

**Comment by flick0** [comment]
and about the waybar issue, it should be synced up to your system clock so try checking if the system clock is correct if it is then i think its probably a waybar issue

**Comment by kamaterasu** [comment]
> fixed the wallpaper in [`234d098`](https://github.com/flick0/dotfiles/commit/234d0984e9dbd54989b983344b91decb568f3b27)
> 
> 
> 
> wdym it takes screenshot? do u see the slurp gui?

There is a notification top right saying screenshot saved at etc.

**Comment by kamaterasu** [comment]
Also in hypr config there is shortcut that open donut.c where is c file needed to have in just ~/.config/hypr?

**Comment by flick0** [comment]
> Also in hypr config there is shortcut that open donut.c where is c file needed to have in just ~/.config/hypr?
`donut.c` is an aur pkg for the rotating donut 

> There is a notification top right saying screenshot saved at etc.
ah, looks like its just displaying the last notification, not actually taking a screenshot

**Comment by flick0** [comment]
ive added a line to autostart so it greets the user using notify-send, that notification should stop the previous notification from appearing
