### ISSUE TITLE
top bar dont show

### ISSUE THREAD

**Issue by VenomLightpro** [flick0/dotfiles#11]
top bar nope,what i can do?

**Comment by flick0** [comment]
did you install the dependencies (waybar), does the bar not come up at all or does it just show up after a long time, if so then you probably have multiple xdg desktop portals installed. check  [this](https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580) guide or try installing the [hyprland desktop portal](https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/) and uninstalling any other desktop portals you have

**Comment by VenomLightpro** [comment]
lol yes, i install it and i fix it,but icons nope

**Comment by VenomLightpro** [comment]
yes i install it, im fix
