### ISSUE TITLE
nope icons

### ISSUE THREAD

**Issue by VenomLightpro** [flick0/dotfiles#12]
![image](https://user-images.githubusercontent.com/98227689/209853348-5e4dc16d-c730-4ae2-be8f-a4064ba1f27b.png)

program icons (1,2,3 ....)

**Comment by flick0** [comment]
you need to get the waybar-hyprland-git pkg

**Comment by flick0** [comment]
regular waybar doesnt support hyprland workspaces

**Comment by VenomLightpro** [comment]
thx, i fix it)
