### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by mentamortem** [flick0/dotfiles#15]
![image](https://user-images.githubusercontent.com/119333794/215474878-466beab3-410f-47c2-9ee8-4f220bdde038.jpeg)

**Comment by flick0** [comment]
you need nerd fonts

**Comment by flick0** [comment]
https://www.nerdfonts.com/font-downloads

**Comment by mentamortem** [comment]
all?

**Comment by mentamortem** [comment]
oh ok, fixed.
