### ISSUE TITLE
Hey flicko

### ISSUE THREAD

**Issue by LUISMAGAIVER341** [flick0/dotfiles#16]
How you created this rice????

**Comment by yavko** [comment]
> How you created this rice????

By moving electricity as impulses from his brain throughout his body, and specifically into his hands to type, those impulses were to write configurations for different programs, and scss styling for his bar. His brain sent out millions of impulses of electricity, and his muscles used up much energy as to move his hands, his brain sent many impulses to his muscles to contract this fingers, thus creating a typing motion. Eventually from all the impulses from his brain and the work of the muscles in his arms responsible for his fingers, he eventually came out with the result of a rice, an expression of his brain impulses.

**Comment by rubyowo** [comment]
was flicko's body tired after sending the impulses?

**Comment by flick0** [comment]
lol, as @yavko said, you kind of just do it, its just writing configs for various tools

**Comment by yavko** [comment]
> was flicko's body tired after sending the impulses?

I just received intel , and it seems due to the hours of contractions and impulses his body indeed was tired

**Comment by flick0** [comment]
> and it seems due to the hours of contractions and impulses his body indeed was tired

if u do everything in one go, the body will be very much tired
but if space out the intense typing, your body will be very much tired but on different intervals

**Comment by LUISMAGAIVER341** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Yavor ***@***.***>
Enviado:domingo, 19 de fevereiro de 2023 02:49
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [flick0/dotfiles] Hey flicko (Issue #16)


How you created this rice????

By moving electricity as impulses from his brain throughout his body, and specifically into his hands to type, those impulses were to write configurations for different programs, and scss styling for his bar. His brain sent out millions of impulses of electricity, and his muscles used up much energy as to move his hands, his brain sent many impulses to his muscles to contract this fingers, thus creating a typing motion. Eventually from all the impulses from his brain and the work of the muscles in his arms responsible for his fingers, he eventually came out with the result of a rice, an expression of his brain impulses.

**Comment by LUISMAGAIVER341** [comment]
Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: Yavor Kolev ***@***.***>
Enviado: Sunday, February 19, 2023 2:48:53 AM
Para: flick0/dotfiles ***@***.***>
Cc: LUISMAGAIVER341 ***@***.***>; Author ***@***.***>
Assunto: Re: [flick0/dotfiles] Hey flicko (Issue #16)


How you created this rice????

By moving electricity as impulses from his brain throughout his body, and specifically into his hands to type, those impulses were to write configurations for different programs, and scss styling for his bar. His brain sent out millions of impulses of electricity, and his muscles used up much energy as to move his hands, his brain sent many impulses to his muscles to contract this fingers, thus creating a typing motion. Eventually from all the impulses from his brain and the work of the muscles in his arms responsible for his fingers, he eventually came out with the result of a rice, an expression of his brain impulses.

**Comment by yavko** [comment]
Huh

**Comment by LUISMAGAIVER341** [comment]
@yavko you are "cringe" and second, i questionated @flick0 and three, you are a shit

**Comment by yavko** [comment]
> @yavko you are "cringe" and second, i questionated @flick0 and three, you are a shit

Oh no what am I going to do, I'm cringe 😬. Also It's not my fault you are asking an irrelevant question, you can't explain how you make a rice, you just do, you write configs, and that's it. There's nothing else to it. It's also its a bit harsh to respond that I'm "shit", I was just being a bit sarcastic. And finally this is not how you use GitHub issues, issues are for actual issues related to the project, this is a personal question, and not related to the project. If you wanna know how to rice maybe trying searching it up. Also sorry if I offended you, or annoyed you, but at least I answered your question in my message of  joking around.

**Comment by yavko** [comment]
> Enviado do Email<[go.microsoft.com/fwlink/?LinkId=550986](https://go.microsoft.com/fwlink/?LinkId=550986)> para Windows

Also if this means you use Windows (which seems likely you do, as your github is filed with VB.NET), then good luck, this rice is for Linux, and Hyprland only. Good luck ricing windows lol. And if you are using Windows, maybe reconsider, Windows is the truest of shit.

**Comment by flick0** [comment]
> @yavko you are "cringe" and second, i questionated @flick0 and three, you are a shit

My answer is still a bit simmilar to yavko

There's no one way u make a rice, your question is very vague and doesn't have a definite correct answer, if you want to know more about any "part" of the rice (like a component of bar perhaps) then that can be a valid question with a valid answer

I assume u wanted me to explain about all the components, then here:

The rice uses hyprland as the compositor/wm on wayland

 The top bar is waybar, It uses a json file for the layout of each module, then used scss which is basically css to style the bar (the moving gradients are done using css animations and a scrolling gradient border)

now coming to windows, the only thing here wud be the borders, it uses gradient borders configured through hyprland's config file (usually at ~/.config/hypr/hyprland.conf)

And about the animations, they also are a part of hyprland config and use a bezier curve that's set in config

As for the wallpapers, I use a wallpaper daemon called swww and it has some nice wallpaper transitions

The audio visualizer if you are wondering, is a program called `cava`, some fun cli scripts used in most of my rices are:

+ pipes.sh
+ cbonsai
+ donut.c

Now coming to the shell
I use `pokemon-colorscripts` from aur which I set in fish.conf to autorun everytime the shell starts up(ie a new terminal opening)

And the prompt, i use starship for that and the config file can be located at `~/.config/starship.toml`

Most of these things can be known just by looking at some of my configs or the wiki for said software, if you want to know more about what programs are used in this rice then take a look at all the dependacies we are installing from the readme


But at the end of the day, it is just "writing configs for various tools"

Here are some useful links:

+ https://wiki.hyprland.org/
+ https://github.com/Alexays/Waybar/wiki
+ https://github.com/Horus645/swww
+ https://github.com/fosslife/awesome-ricing#show-off-scripts

**Comment by yavko** [comment]
Also [unix p***](reddit.com/r/unixporn/) has a lot of rices you can yoink stuff from.
