### ISSUE TITLE
Bar Components Missing

### ISSUE THREAD

**Issue by AdityaRoot** [flick0/dotfiles#20]
Heya, thanks for the incredible rice, flick0! Made swapping from X11 and Qtile so so so much easier!

One issue I'm having while modifying the bar, is that a lot of the components are missing. I'm not sure if I'm just blind and accidentally missed them being commented out! But here is what my bar looks like right now:
![image](https://user-images.githubusercontent.com/66115252/230779144-080f6cf4-905a-48d0-892c-3323780c061d.png)

So components such as battery, backlight, and most importantly the systray are missing. I'm sure this is just some code oversight on my part but I'd super appreciate any guidance as to where I can approach solving the issue!

(As an unrelated note, might be useful to set the 'sort numerically' value for waybar! Otherwise the workspaces come up in the order 1, 10, 2, 3... - unless of course this is intentional, happy to throw up a pr if not)

**Comment by flick0** [comment]
yep they pop up when they actually have something to display

for battery indicator, it is displayed only when ur battery is discharging
and a red wifi icon is showed when wifi has been disconnected
