### ISSUE TITLE
Missing Cava Module?

### ISSUE THREAD

**Issue by lee-morgan** [flick0/dotfiles#24]
Hi flick0,

I have to say I love the dreamy rice.  I have pretty much got it all working now but I seem to be missing the cava module on waybar? How do I add that please?

Many thanks for all your hard work, it's greatly appreciated.

Regards
Lee

**Comment by flick0** [comment]
that module you are talking about isnt cava, rather its just cpu load
if you are looking for a modified version of this bar with cava and alot more stuff then check out [SimplyKyle](https://gitea.com/SimplyKyle/dotfiles/src/branch/main/home/.config/waybar)'s dotfiles
