### ISSUE TITLE
Just did a fresh install and it seems to be not working (Beginner on Hyprland)

### ISSUE THREAD

**Issue by DiogoChrispim** [flick0/dotfiles#27]
![image](https://github.com/flick0/dotfiles/assets/136935343/b83cfe3d-b60a-421c-9cef-ade85c855e09)

any help?

**Comment by flick0** [comment]
hyprland changed how blur config is written, you can either remove the configs related to blur in hyprland.conf or move them under decorations.blur

**Comment by Ptitlu42** [comment]
hello, I have the same problem, I didn't understand how to fix it, clarification please?

**Comment by mag4no10** [comment]
> hello, I have the same problem, I didn't understand how to fix it, clarification please?

In hyprland.conf, remove the configs related to blur or add them in this section
decoration {
     blur {
          blur configs like "enabled = true", "size = 10" etc
     }
}
