### ISSUE TITLE
waybar not starting

### ISSUE THREAD

**Issue by zebogan** [flick0/dotfiles#28]
i just followed the instructions to install all the stuff. haven't changed anything, but waybar just isn't starting. it's in autostart. one potential issue is that i installed waybar through pacman -S waybar instead of using paru because paru just would fail to install it every time. let me know if more info is needed.

**Comment by zebogan** [comment]
nvm fixed it

**Comment by Zenith-the-realest** [comment]
how'd you fix it?

**Comment by zebogan** [comment]
i don't remember tbh
