### ISSUE TITLE
File manager

### ISSUE THREAD

**Issue by KitKat-ok** [flick0/dotfiles#29]
Whats the file manager used in the video and what theme it uses ?

**Comment by flick0** [comment]
its nautilus with the catppuccin gtk theme

**Comment by KitKat-ok** [comment]
it looks like this for me 
![Screenshot from 2023-09-25 15-44-47](https://github.com/flick0/dotfiles/assets/78702592/7aa07fbe-065c-44ce-a4b5-369d09f36b15)

**Comment by flick0** [comment]
Try the gradience version of catppuccin

**Comment by KitKat-ok** [comment]
I already have that and what gtk theme are you using [https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme](url) this or [https://github.com/catppuccin/gtk](url) ??

**Comment by flick0** [comment]
oh, it must be this one [https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme](https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme)

ive reinstalled my system(multiple times) after making that rice so didnt really remember the theme

**Comment by KitKat-ok** [comment]
oh okay it works
