### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by Borber** [flick0/dotfiles#3]
Can you provide a list of the fonts that need to be installed?

**Comment by flick0** [comment]
it uses cartographcf

**Comment by nulloneguy** [comment]
I have a font problem. Font the right one and the icons in the terminal are still crooked
![image](https://user-images.githubusercontent.com/87767572/205045102-1fe6ff5e-937d-400b-938e-184f338d81bc.png)

**Comment by flick0** [comment]
you will need nerd fonts for that
