### ISSUE TITLE
[Yorha] Black Screen After copying the Files

### ISSUE THREAD

**Issue by RookiexCookie** [flick0/dotfiles#36]
Hey i know that you been working on this Super Cool Hyprland config for a long time and it just dropped .

but i have a problem ,I made a new user just for this and after logging into new hyprland session and doing what the readme instructed which was installing , cloning and copying, 
after copying the files from the temp to main .config/hypr
it refreshed and it went black except for the terminal and firefox  but  no wallpaper no bar , only mod+q , mod + l and mod +m to quit was working
not sure whats happening there 
tried rebooting ,reinstalling and cloning a few times , didnt seemed to work :/

so what should i do

**Comment by flick0** [comment]
did you also install the base theme (main branch), is mod+q opening terminal? cuz mod+q is for quitting apps on base theme

**Comment by flick0** [comment]
also try starting ags manually, the cmd shud be 
```sh
ags -c ~/.config/hypr/themes/nier/components/ags/config.js
```

**Comment by RookiexCookie** [comment]
> did you also install the base theme (main branch), is mod+q opening terminal? cuz mod+q is for quitting apps on base theme
i dont think so, how do i do that
i only did what https://github.com/flick0/dotfiles said in the readme

**Comment by RookiexCookie** [comment]
Sweet 
thanks, i will go do that

**Comment by RookiexCookie** [comment]
![image](https://github.com/flick0/dotfiles/assets/136296017/7d08434e-e78c-494e-b20f-490844f1c620)

uhh something wrong with the resolution

**Comment by RookiexCookie** [comment]
> also try starting ags manually, the cmd shud be
> 
> ```shell
> ags -c ~/.config/hypr/themes/yorha/components/ags/config.js
> ```

yea i added that to one of the exec-once

**Comment by RookiexCookie** [comment]
ugh this mouse i swear

**Comment by flick0** [comment]
hmmmm wierd, do u have multiple monitors?

**Comment by RookiexCookie** [comment]
no i dont have multiple monitors

resolution of my monitor
   1366x768      59.80*+

**Comment by flick0** [comment]
did you set your resolution at `~/.config/hypr/profiles/power.conf` and `~/.config/hypr/profiles/battery.conf`

**Comment by RookiexCookie** [comment]
![image](https://github.com/flick0/dotfiles/assets/136296017/a1b1fc59-5b75-4352-9edc-ca145b6a191b)

it was in 4k resolution for some reason 
after i change that and rebooted 
it still like this

**Comment by Lumenohr** [comment]
Hitting a similar issue with the rice's resolution as well as an issue with ags launching its widgets on a fresh 1920x1080@60 arch install:
![20240107_04h14m12s_grim](https://github.com/flick0/dotfiles/assets/149939320/17a37d02-c1b6-4a81-be93-63293a504a3b)

**Comment by flick0** [comment]
The ags windows opening as actual windows is a thing with hyprbars ig, adding a delay to ags should work fine.

As for the wierd resolution, it might either be fonts or me being dum and hard coding the sizes

**Comment by flick0** [comment]
Also can you check if the settings menu buttons are messed up aswell?

**Comment by YesIndeed** [comment]
![20240106_18h43m19s_grim](https://github.com/flick0/dotfiles/assets/2481615/273d56eb-b76b-46c4-ba32-8d7e253ddeff)

I'm encountering some issues with trying to install this on a fresh arch install: the hyprbar, decorative borders, and other UI elements do not load after following instructions. 

So far, I've also attempted to adjust the resolution to 1920 x 1080 to match my monitor in power.conf and battery.conf per above comments. Seeking insight for why these do not seem to want to work. Thanks.

**Comment by flick0** [comment]
Check if you can start them manually with
```
pkill ags && ags -c ~/.config/hypr/themes/nier/components/ags/config.js
```

**Comment by flick0** [comment]
87a7c76140bce057de79ac540d4ca2cafba106a0 should fix the ags startup problems

**Comment by RookiexCookie** [comment]
> Check if you can start them manually with
> 
> ```
> pkill ags && ags -c ~/.config/hypr/themes/nier/components/ags/config.js
> ```

shouldnt that be ~/.config/hypr/themes/yorha/components/ags/config.js
?

**Comment by flick0** [comment]
Ahh yes mb, I keep forgetting I changed the name from nier to yorha

**Comment by YesIndeed** [comment]
Attempted to checkout https://github.com/flick0/dotfiles/commit/87a7c76140bce057de79ac540d4ca2cafba106a0 and install base config from there, per documentation:

```
git clone https://github.com/flick0/dotfiles /tmp/flick0-dotfiles
git checkout 87a7c76
cd /tmp/flick0-dotfiles && cp -r ./config/* ~/.config/
```

Then re-enabled the theme by changing the `$THEME` variable and restarted. Separately attempted to manually restart ags like:
```
pkill ags && ags -c ~/.config/hypr/themes/yorha/components/ags/config.js
```

I'm noticing on startup I get a dialog that states that the hyprbar has initialized, but it does not display: decorative borders and hyprbar continues to be blank.

**Comment by flick0** [comment]
Oh that's the wrong commit hash (dk how that happened) and the wrong branch too

Just git pull on hyprland-yorha branch inside ~/.config/hypr/themes/yorha

**Comment by flick0** [comment]
The only thing that changed was the exec line on theme.conf to
```
exec-once=sleep 1 && pkill ags && ags -c $THEME/components/ags/config.js
```

**Comment by flick0** [comment]
also added a delay to loading hyprbars, since it interfered with ags startup

**Comment by flick0** [comment]
sorry @RookiexCookie but ill prolly have to redo how sizing works to fix the wierd res and it might take a while since im a lil busy irl for a few days

**Comment by RookiexCookie** [comment]
its alright mate , its still pretty amazing
Have a good day
