### ISSUE TITLE
Question about vscode :)

### ISSUE THREAD

**Issue by vethyn** [flick0/dotfiles#4]
Hey,

your setup looks awesome :). Would you mind sharing what addons/plugins you used beside the Custom CSS part? :) Or maybe post "relevant" parts of your settings.json.

Greetings
Moritz

**Comment by flick0** [comment]
have you checked [this](https://github.com/flick0/dotfiles/tree/dreamy#vscode-custom-css)?

**Comment by vethyn** [comment]
Yeah :) i thought this is vscode:

![image](https://user-images.githubusercontent.com/114048565/196728000-dc5ee3b8-f9a8-49d0-a98d-55c1b8bb4a20.png)

but i think this is bat :), and was confused what you also did to get vscode look like this :).

Greetings
Moritz

**Comment by 0xSnoxzy** [comment]
Hey vethyn, how dod you started the graphical interface? im stuck on the tty after the installation of all the things

**Comment by flick0** [comment]
> Hey vethyn, how did you started the graphical interface? im stuck on the tty after the installation of all the things
> 
> 

You have to logout and login to hyprland using ur login manager( there shud be a drop-down somewhere) also use sddm if anything is bugging out

**Comment by vethyn** [comment]
or try to execute hyprland from the tty :), i don't use sddm or so :).

Greetings

**Comment by 0xSnoxzy** [comment]
ok, thank you very much, im going to try it

**Comment by 0xSnoxzy** [comment]
ok, i tried logging out and relogging in with hyprland but it returns automatically to the login screen without showing anything

**Comment by flick0** [comment]
> ok, i tried logging out and relogging in with hyprland but it returns automatically to the login screen without showing anything

ye, you probably need to use sddm then
