### ISSUE TITLE
Workspace numbers and dark mode

### ISSUE THREAD

**Issue by ivopr** [flick0/dotfiles#43]
Hey there, first of all, thanks for sharing these awesome configs. Just trying it now and it's almost seamless.

So, by default we start with 10 workspaces, I'm fine with that and all, except that when I move the mouse it becomes like this:
![image](https://github.com/flick0/dotfiles/assets/30270448/d6451153-d7c1-4ff5-91a5-9f6920fb0ce4)

And I've been reading things on the code and about hyprland and did not manage to get to change the theme. Maybe I'm just not seeing something obvious though.

**Comment by flick0** [comment]
the buttons become longer/get more spacing between them? hmmmm i used to have this issue long ago but it mysteriously fixed itself. can you tell me your screen res, and also did you update the resolutions in both the files in ~/.config/hypr/profiles

**Comment by ivopr** [comment]
@flick0 ohh that may be it, I'm on 1920x1080, didn't see the res there

**Comment by flick0** [comment]
you also wud need to set your res at ~/.config/hypr/themes/yorha/components/ags/style/data.scss

( i really need to find a way to gen these files automatically )

**Comment by ivopr** [comment]
@flick0 if you just leave it a default would it work? like `monitor=,preferred,auto,1`

**Comment by flick0** [comment]
yes, i had to put screen res there to be able to set a custom refresh rate (60hz on battery and 165 when plugged in)

**Comment by ivopr** [comment]
> yes, i had to put screen res there to be able to set a custom refresh rate (60hz on battery and 165 when plugged in)

ohh, that makes sense.

anyway, didn't work, if I open up wofi with `Super+Space` the topbar shows correctly, but as soon as I move the mouse around it becomes what is in the screenshot again

**Comment by flick0** [comment]
hmmm, then it might be cuz of me being dum and hardcoding some sizes,  seems like its similar to #36

but as i told in that issue as well, i will be busy for a couple days so it might take a while to redo the sizes and stuff

**Comment by ivopr** [comment]
no problem, the first screenshot there is how It is, the dotted line below the workspaces doesn't go full width when all workspace buttons are visible.

And how would you toggle from light to dark?

**Comment by flick0** [comment]
by opening the settings menu and clicking the button at the bottom, you mentioned Super+space opens wofi right?, its supposed to open the settings menu, or you can also press the red button to the right of workspaces if it isnt hidden

**Comment by flick0** [comment]
are u using the latest hyprland?

**Comment by ivopr** [comment]
> are u using the latest hyprland?

supposedly, `hyprland-git` aur.

is this the settings menu?
![image](https://github.com/flick0/dotfiles/assets/30270448/2ade9afb-e5fc-42e2-bcd9-6f832b978b11)

**Comment by flick0** [comment]
the bottom part of settings menu is cut off, it should compile the styles when you start ags

**Comment by flick0** [comment]
another way is to run the cmd manually
```
ags -b banner -c ~/.config/hypr/themes/yorha/components/ags/windows/banner/banner.js
```

or without animations
```
ags -r "dark.value=false"
```

**Comment by ivopr** [comment]
> the bottom part of settings menu is cut off, it should compile the styles when you start ags

then everything's okay, I'll move the placement of these things for the time being then.

thank you for taking the time to answer me tough.

**Comment by flick0** [comment]
ive added some scaling options at `~/.config/hypr/themes/yorha/components/ags/scaling.js` you can now tweak the options to scale most of the widgets, also the workspaces/settings pane shudnt just glitch out and be scrollable depending on screen size

@RookiexCookie @ivopr

**Comment by VarLad** [comment]
@flick0 May I recommend, just use normal `hyprland` in the dependencies (thats way more recent than hyprland-git`) and replace `hyprland-plugins-hyprbars-git` with the inbuilt one from `hyprpm`

Also the install.sh file is broken as of now because of this

**Comment by flick0** [comment]
> @flick0 May I recommend, just use normal `hyprland` in the dependencies (thats way more recent than `hyprland-git`) and replace `hyprland-plugins-hyprbars-git` with the inbuilt one from `hyprpm`
> 
> Also the install.sh file is broken as of now because of this and other reasons.

Hyprland-git is more recent than hyprland it's just the aur version number doesn't change

hyprpm has been having issues on my system and the aur pkg seems to do the same thing

What exactly is broken on install.sh?

**Comment by VarLad** [comment]
```
:: Calculating inner conflicts...

:: Conflicts found:
    hyprland-git: hyprland

:: Conflicting packages will have to be confirmed manually
error: can not install conflicting packages with --noconfirm
```

and

```
mkdir: cannot create directory ‘/home/username/.config/hypr/themes’: File exists
bash: line 31: ./themes/yorha: No such file or directory
```

**Comment by flick0** [comment]
+ uninstall `hyprland` and install the git version

+ second error should be fixed in latest commit

**Comment by RookiexCookie** [comment]
> ive added some scaling options at `~/.config/hypr/themes/yorha/components/ags/scaling.js` you can now tweak the options to scale most of the widgets, also the workspaces/settings pane shudnt just glitch out and be scrollable depending on screen size
> 
> @RookiexCookie @ivopr


Great news
will check it out

**Comment by VarLad** [comment]
@flick0 Any way that it doesn't alter my existing GNOME theme?

**Comment by flick0** [comment]
It shouldn't alter anything outside the hyprland folder
