### ISSUE TITLE
ags errors, refuses to work.

### ISSUE THREAD

**Issue by Syvar** [flick0/dotfiles#45]
First off, the setup looks amazing, thank you for your hard work.

I'm using `aylurs-gtk-shell-git 1.6.3.beta.r20.gf681ba2-1` and `hyprland-git 0.34.0.r34.f92a86af-1` on Archlinux.

Ags seems to have some issues though, can't tell if it's the configs' problem or my mistake, and everything I've tried doesn't seem to fix it.
What happens is that on Hyprland launch, ags doesnt appear at all. Trying to run it through a terminal returns: `Ags with busname "ags" is already running`
So my next though is `pkill ags` and `ags -c .config/hypr/themes/yorha/components/ags/config.js` which returns: 
`(ags:102511): Gjs-WARNING **: 15:19:49.234: JS ERROR: ImportError: Unable to load file from: file://.config/hypr/themes/yorha/components/ags/config.js (Operation not supported)
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

Moving all the files from `.config/hypr/themes/yorha/components/ags/` to `./config/ags/` and running just `ags` returns:
`(ags:103051): Gjs-WARNING **: 15:29:38.516: JS ERROR: ImportError: Unable to load file from: resource:///com/github/Aylur/ags/service.js (The resource at “/com/github/Aylur/ags/service.js” does not exist)
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:88:21
loadURI@resource:///org/gnome/gjs/modules/internal/loader.js:290:30
resolveModule@resource:///org/gnome/gjs/modules/internal/loader.js:179:33
moduleResolveHook@resource:///org/gnome/gjs/modules/internal/loader.js:339:29
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

At this point I'm stumped. I'm not the most technical person in the world and I couldn't find a fix online. Is this an error on my side? Any help would be appreciated as I love Automata and the theme looks fantastic. If you need any logs or any other info please let me know.

**Comment by flick0** [comment]
this was resolved on discord 

![Screenshot_20240110-104105.png](https://github.com/flick0/dotfiles/assets/77581181/00d0f86b-c647-4564-a0bc-d070969b3a1c)
