### ISSUE TITLE
How to show AGS bar on multiple monitors

### ISSUE THREAD

**Issue by scorypto** [flick0/dotfiles#46]
First of all, one of the most awesome Rice in my opinion.

 I generally use multi monitor setup. AGS bar is working nicely on single laptop screen, How can I modify the config so that I can get AGS bar on both monitors I'm using.

**Comment by flick0** [comment]
i havent really tested multiple monitors but you can try doing something like this in config.js
![image](https://github.com/flick0/dotfiles/assets/77581181/4c46b1ec-dda8-4c39-8fd8-ec14fcea274b)

**Comment by scorypto** [comment]
Awesome Thanks, let me try.
