### ISSUE TITLE
Issues with ags

### ISSUE THREAD

**Issue by OohSorry** [flick0/dotfiles#49]
No animations on the right side of the player. Also, when you change the colorscheme, the background does not change to the appropriate one. swww init can help with background but idk what to do with cava with player.

**Comment by OohSorry** [comment]
So, I checked and also recreated symlink because it looks like broken.Recreated between ```.config/hypr/themes/yorha/components/ags/scripts/cava``` and ```.config/hypr/themes/yorha/components/ags/windows/player/scripts/cava``` but it didn't helped.

**Comment by flick0** [comment]
hmmm, recreating the symlink shudv fixed it ( i totally forgot i had a symlink there, will fix on the repo ) can you run `ags -b player -c ~/.config/hypr/themes/yorha/components/ags/windows/player/player.js` and check its logs

**Comment by flick0** [comment]
did you make the cava file an executable btw?

**Comment by OohSorry** [comment]
Uhmm, I'll check it. What about issue with background change on changing theme?

**Comment by OohSorry** [comment]
> did you make the cava file an executable btw?

Oh I forgot to do that. Gonna check it all little bit later. What about issue with background change on changing theme?

**Comment by flick0** [comment]
i dont seem to be able to reproduce the background change, does it happen often for you?

badapple does work but it might be lil buggy

**Comment by OohSorry** [comment]
> i dont seem to be able to reproduce the background change, does it happen often for you?
> 
> badapple does work but it might be lil buggy

It's okay if I wanna switch I just '''swww init''' to another bg

**Comment by OohSorry** [comment]
Yep, ```chmod +x``` worked. Appreciate very much.
Also all vars for badapple in ```nowplaying .js``` is 0 or false. Is it how it supposed to be?

**Comment by flick0** [comment]
Ye, they shud get their values when bad apple on bring played tho
