### ISSUE TITLE
None of the widgets show 

### ISSUE THREAD

**Issue by Zenith-the-realest** [flick0/dotfiles#50]
Firstly, I absolutely love this - Nier Automata is a really cool game and I love how this looks. Sadly, even after following the instructions, and attempting to use the install script, I do not get any widgets like the workspace options or the settings are visible. I have already installed the base config in the master branch, and have configured my monitor's resolution.  This is all I see:
![image](https://github.com/flick0/dotfiles/assets/75748674/8475b7fd-3608-461c-ba09-dfcb84cc2d1e)
Edit: Hyprbar does send the notification saying that it's initialised, and notifications also don't send, like the one that should notify me about a screenshot.

**Comment by OohSorry** [comment]
Widgets doesn’t show because of hyprbar. I suggest you remove hyprbar via “paru -R hyprland-plugin-hyprbars-git”. And reinstall it with build hyprland’s plugin manager “hyprpm”.

**Comment by OohSorry** [comment]
Also check readme. I made a pull request yesterday. There was new package that needed for working screenshot script.

**Comment by Zenith-the-realest** [comment]
I have removed it using paru, and installed it with hyprpm. The bar on top of windows shows, but the widgets still don't show. And by screenshotting, I mean the notification that sends when a screenshot is taken doesn't show up; the copying to clipboard is fine.

**Comment by Zenith-the-realest** [comment]
Also, running `pkill ags && ags -c ~/.config/hypr/themes/yorha/components/ags/config.js` only returns:
```
(com.github.Aylur.ags:65453): Gjs-WARNING **: 19:51:34.637: JS ERROR: Error: Requiring GnomeBluetooth, version 3.0: Typelib file for namespace 'GnomeBluetooth', version '3.0' not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://GnomeBluetooth/?version=3.0:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by OohSorry** [comment]
Oh, I see. I have gnome-bluetooth 3.0. Installing 3.0 version should help. You can try -S gnome-bluetooth-3.0
I currently have 3.0. 42.7-2 from aur

**Comment by OohSorry** [comment]
Try reinstall gnome-bluetooth then

**Comment by Zenith-the-realest** [comment]
that worked, thank you so much! now i just need to fix my resolutions: where do i edit them?

**Comment by OohSorry** [comment]
So. As I know there is 3 places where you need to change it. 1 and 2 is in hypr/profiles directory in files battery.conf and power.conf. Also change @60 to your refresh rate. Last one in ~/.config/hypr/themes/yorha/components/ags/style/data.scss

**Comment by Zenith-the-realest** [comment]
I have edited these to 1920x1080@60 on battery.conf and power.conf, along with editing ~/.config/hypr/themes/yorha/components/ags/style/data.scss, but it still appears stretched / weird.

**Comment by OohSorry** [comment]
Have you tried logout and log in? Or restart

**Comment by Zenith-the-realest** [comment]
I've tried both.

**Comment by OohSorry** [comment]
Hmm, can I see screenshot?

**Comment by Zenith-the-realest** [comment]
Empty background:
![image](https://github.com/flick0/dotfiles/assets/75748674/4d4784be-d054-4429-92bd-f33c35659918)
With window open:
![image](https://github.com/flick0/dotfiles/assets/75748674/231ff71c-6b8e-4ec6-8f11-1ba16a05b429)

you can see it peeking through

**Comment by OohSorry** [comment]
I’m not sure about that moment but I think that problem comes from hyprland. Because there is no waybar and workspaces made on ags soo.. I think you need to edit some configs for windows in hyprland. Variables like gaps_in and gaps_out in these configs should help. I see I also have same issue but I don’t care it’s fine for me. It’s should help with peeking workspaces

**Comment by OohSorry** [comment]
You can try lower values for gaps_out

**Comment by OohSorry** [comment]
I found solution for this. you need to change "monitor" variable in .config/hypr/themes/yorha/theme.conf
Just adjust eDP-1 to your current monitor. For me it's HDMI-A-1. Use "xrandr" for check your monitor. Flick0 already made custom reserved area but forgot to say other to change this too.

**Comment by OohSorry** [comment]
This issue can be closed I think.

**Comment by flick0** [comment]
> So. As I know there is 3 places where you need to change it. 1 and 2 is in `hypr/profiles` directory in files `battery.conf` and `power.conf` Also change @60 to your refresh rate. Last one in `~/.config/hypr/themes/yorha/components/ags/style/data.scss`

the resolutions at data.scss should be auto generated now

> Flick0 already made custom reserved area but forgot to say other to change this too.

ah i totally did ;-;
ill try auto genning that as well

**Comment by flick0** [comment]
@Zenith-the-realest you can also try messing around with scaling at ~/.config/hypr/themes/yorha/components/ags/scaling.js to reduce button sizes and such if they are too big ( they look big on your screenshots )

**Comment by flick0** [comment]
> ill try auto genning that as well

done  in the latest commit
