### ISSUE TITLE
Is `ags` the dependency of this project

### ISSUE THREAD

**Issue by TimePrinciple** [flick0/dotfiles#51]
If `ags` is a dependency of this project, I wonder which `ags` (`ags` or `ags-git`) should be installed, and why it's not in the dependency list.

**Comment by TimePrinciple** [comment]
I'm getting this error when manually starting ags:
```
(com.github.Aylur.ags:1788): Gjs-WARNING **: 18:23:01.229: JS ERROR: Error: Requiring DbusmenuGtk3, version none: Typelib file for namespace 'DbusmenuGtk3' (any version) not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://DbusmenuGtk3:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```
Any ideas how to fix this

**Comment by Zenith-the-realest** [comment]
Try install `dbusmenu-gtk3` for whatever OS you are using

**Comment by TimePrinciple** [comment]
I'm using Arch linux and I failed to find a package named that.

> Try install `dbusmenu-gtk3` for whatever OS you are using

**Comment by TimePrinciple** [comment]
I'm using Arch linux and I failed to find a package named that.

> I'm using Arch linux and I failed to find a package named that.
> 
> > Try install `dbusmenu-gtk3` for whatever OS you are using

I found the package named `libdbusmenu-gtk3`, and it can be installed by `paru` or whatever uses AUR as its source.
I'm curious what am I missing along the way of installing causes this package not being installed.

**Comment by TimePrinciple** [comment]
I wonder whether this project needs any of the packages in `libdbusmenu-gtk3` ->  `waybar` -(optional)-> `sway` -(optional)-> `foot`. I just saw `foot` is in the dependency list but when I install it with `paru`, it did not install `libdbusmenu-gtk3`.

**Comment by Zenith-the-realest** [comment]
try install libdbusmenu-gtk3 and see how that fares

**Comment by TimePrinciple** [comment]
> try install libdbusmenu-gtk3 and see how that fares

After install `libdbusmenu-gtk3` package, everything go back to normal and works fine, I'm wondering how I missing this package that causes a lot of problems.

**Comment by flick0** [comment]
many ppl have been having issues with `libdbusmenu-gtk3` and `gnome-bluetooth-3.0` ( which seem to be preinstalled in some distros? ) ill add them as dependencies in readme anyways
