### ISSUE TITLE
Only wallpaper screen appear after install dotfiles. 

### ISSUE THREAD

**Issue by orcbolg3612** [flick0/dotfiles#53]
I following the instructions, reboot and. 
![image](https://github.com/flick0/dotfiles/assets/154581201/305bd5ee-8254-4ae6-8078-a3dca3b3f079)
The only thing that i can do is press Mod+E to open thunar and mod+q to close it

**Comment by flick0** [comment]
You might need to install portals, hyprland's portal is `xdg-desktop-portal-hyprland`

**Comment by orcbolg3612** [comment]
> Can you try running ags manually, open terminal(super+enter) and type this `pkill ags ; ags -c ~/.config/hypr/themes/yorha/components/ags/config.js`

Can i run this command in gnome desktop?

**Comment by flick0** [comment]
No run it in hyprland
