### ISSUE TITLE
Top bar, System menu, notifications not working.

### ISSUE THREAD

**Issue by LounaCodes** [flick0/dotfiles#55]
Hello, I have installed this rice from a fresh minimal arch install via the install script. I followed all the steps from the readme, but several things are not working yet. 
Even after looking at several issues, with the top bar, I couldn't resolve my issue of not seeing it at all.  The System menu showcased in your youtube viedeo like this:
![Your showcase on Youtube](https://github.com/flick0/dotfiles/assets/119534727/03f70d29-a3be-4501-b541-d7b6a632f93a)
Does not show up (how is it started/configured?)
trying to send a dummy notification just gives me this error:
`notify-send "message" "more message"`
-> `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable`

The Screenshot tool acts really weird with 2 monitors, it . Is this known? Do I need to edit a config file for this? Here are my monitors if they are causing the issue.
monitor=DP-1, 2560x1440@165,1920x-200,1 
monitor = HDMI-A-1, 1920x1080@144, 0x0, 1

The player works great for web play, but on native spotify the album cover doesn't update at all. Also is it supposed to start automatically, because I only got it working after launching it manually with ags.

Not sure if this has something to do with anything named above, but cava doesn't actually show the sounds currently played and only shows something that seems to be a placeholder.

This project is amazing and I would love to get it to work. Is there a Discord server for issues and discussions about this?

Anyway, thanks in advance. I am somewhat new to linux and especially ricing, so I hope this issue isn't too stupid, but after taking a look at some of these issues, I believe, the standart isn't too high for questions.

**Comment by flick0** [comment]
the install script is a little broken right now (its missing some deps) so i recommend doing it manually.

have u tried starting the top bar manually? `ags -c ~/.config/hypr/themes/yorha/components/ags/config.js` if so did it give any errors?

the config for top bar is supposed to start all the other ags windows(settings menu, player, notifications)

does spotify work with other mpris stuff? ags uses mpris to get the music data and if its not working it wud mean its not getting any data from mpris

hmm never tested the rice with multiple monitors, what exactly do u mean by acts wierd?

are u talking about the bars next to the player? they move with a passive slow speed when no music is playing and match their speed with music when it is playing using cava as backend, does `cava` in terminal work?
