### ISSUE TITLE
Line 5 (hyprland.conf) leads to a non-existant file

### ISSUE THREAD

**Issue by Honinbou02** [flick0/dotfiles#56]
Because line 5 of the "hyprland.conf" file says a path to a non-existent file, it gives an error when entering the system "Hyprland may not work correctly"
![Screenshot_20240128_173123](https://github.com/flick0/dotfiles/assets/9055877/42de9651-efde-48a2-be3a-48bdecd6815c)

**Comment by flick0** [comment]
i forgot to comment it out while i was testing hyprtheme and pushed the changes, it should be fixed now
