### ISSUE TITLE
[YoRHa]  Error when installing dependency (hyprland-plugin-hyprbars-git)

### ISSUE THREAD

**Issue by sudo-less** [flick0/dotfiles#58]
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...
:: orphans: hyprland-plugin-hyprbars-git

Aur (1) hyprland-plugins-git-r92.b225987-1 (hyprland-plugin-hyprbars-git)

:: Proceed to review? [Y/n]: Y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: hyprland-plugins-git r92.b225987-1 (Wed 14 Feb 2024 10:30:55 PM -03)
==> Retrieving sources...
  -> Updating hyprland-plugins-git git repo...
==> Validating source files with sha256sums...
    hyprland-plugins-git ... Skipped
==> Making package: hyprland-plugins-git r92.b225987-1 (Wed 14 Feb 2024 10:31:06 PM -03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating hyprland-plugins-git git repo...
==> Validating source files with sha256sums...
    hyprland-plugins-git ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of hyprland-plugins-git git repo...
Cloning into 'hyprland-plugins-git'...
done.
==> Starting pkgver()...
==> Updated version: hyprland-plugins-git r120.d7ee473-1
==> Sources are ready.
hyprland-plugins-git-r92.b225987-1 (hyprland-plugin-hyprbars-git): parsing pkg list...
==> Making package: hyprland-plugins-git r120.d7ee473-1 (Wed 14 Feb 2024 10:31:26 PM -03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
g++ -shared -fPIC --no-gnu-unique main.cpp trail.cpp -o hyprtrails.so -g `pkg-config --cflags pixman-1 libdrm hyprland` -std=c++2b -O2
g++ -shared -fPIC --no-gnu-unique main.cpp -o csgo-vulkan-fix.so -g `pkg-config --cflags pixman-1 libdrm hyprland` -std=c++2b -O2
g++ -shared -fPIC --no-gnu-unique -g -std=c++2b -Wno-c++11-narrowing `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server hyprland` main.cpp barDeco.cpp  -o hyprbars.so `pkg-config --libs pangocairo` -O2
g++ -shared -fPIC --no-gnu-unique main.cpp borderDeco.cpp -o borders-plus-plus.so -g `pkg-config --cflags pixman-1 libdrm hyprland` -std=c++2b -O2
g++ -shared -fPIC --no-gnu-unique main.cpp -o hyprwinwrap.so -g `pkg-config --cflags pixman-1 libdrm hyprland` -std=c++2b -O2
In file included from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/Compositor.hpp:7,
                 from main.cpp:5:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/Compositor.hpp:7,
                 from main.cpp:6:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/Compositor.hpp:7,
                 from main.cpp:6:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/Compositor.hpp:7,
                 from main.cpp:6:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from main.cpp:6:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
make: *** [Makefile:2: all] Error 1
In file included from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:4,
                 from barDeco.hpp:5,
                 from barDeco.cpp:1:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:11: hyprbars.so] Error 1
In file included from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:4,
                 from borderDeco.hpp:5,
                 from borderDeco.cpp:1:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
In file included from /usr/include/hyprland/src/defines.hpp:1,
                 from /usr/include/hyprland/src/render/decorations/IHyprWindowDecoration.hpp:4,
                 from trail.hpp:7,
                 from trail.cpp:1:
/usr/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/util/transform.h: No such file or directory
  108 | #include <wlr/util/transform.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2: all] Error 1
==> Entering fakeroot environment...
==> Starting package_hyprland-plugin-borders-plus-plus-git()...
install: cannot stat 'borders-plus-plus.so': No such file or directory
==> ERROR: A failure occurred in package_hyprland-plugin-borders-plus-plus-git().
    Aborting...
error: failed to build 'hyprland-plugins-git-r92.b225987-1 (hyprland-plugin-hyprbars-git)': 
error: packages failed to build: hyprland-plugins-git-r92.b225987-1 (hyprland-plugin-hyprbars-git)

**Comment by flick0** [comment]
Can you try using hyprpm to install hyprbars instead?
