### ISSUE TITLE
Should I use the master repo or hyprland-yorha ?? & What about other themes are they archived for good ?

### ISSUE THREAD

**Issue by Rafi1018** [flick0/dotfiles#60]
^^^

Also how much RAM is used in your system as idle ??

Thanks

**Comment by flick0** [comment]
You shud get both the master branch and the hyprland-yorha branch.

I'll probably update the archived rices need a few changes for them to work with latest hyprland, I'll prolly update them once to have them work again but it's not very high up on my to-do list

**Comment by flick0** [comment]
My ram usage is usually around like 2-3gigs iirc
