### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by Rafi1018** [flick0/dotfiles#61]
I installed everything from base on arch install in one of my system but after following all the steps & making sure all packages where downloaded properly it seems that nothing is themed (like the terminal & sddm )
Also getting bunch of errors on hyprland.conf ( IDK why but those errors are pointing towards the commented messages

**Comment by flick0** [comment]
What are the errors?

**Comment by Rafi1018** [comment]
> What are the errors?

I didn't see any specific errors it was just ags didn't load but I was able to due to some dependencies missing it's all good now though but some applications like swww doesn't run on startup
