### ISSUE TITLE
(Noobie) How can i set theme to be permanently black?

### ISSUE THREAD

**Issue by artem01molodyk** [flick0/dotfiles#62]
When I start each new session, something strange always happens to the theme. If I ended the last session with a black theme, then drun will look like it is from a white theme and I have to switch between them a couple of times to normalize(Sorry in advance, I used a translator and may have used some words not according to their direct meaning).

**Comment by flick0** [comment]
the theme doesnt store previously set value yet, if you want it to default to dark you can change the value to `true` in these files

https://github.com/flick0/dotfiles/blob/1cf107bcf29dea2f7c6c264e2766f035bf1fc998/components/ags/util.js#L28
https://github.com/flick0/dotfiles/blob/1cf107bcf29dea2f7c6c264e2766f035bf1fc998/components/ags/windows/notifications/notifications.js#L19
https://github.com/flick0/dotfiles/blob/1cf107bcf29dea2f7c6c264e2766f035bf1fc998/components/ags/windows/player/utils.js#L23

the files should be at `~/.config/hypr/themes/yorha/components/ags/util.js`, `~/.config/hypr/themes/yorha/components/ags/windows/notifications/notification.js` and `~/.config/hypr/themes/yorha/components/ags/windows/player/utils.js` respectively

**Comment by artem01molodyk** [comment]
worked! tysm <3
Oh, also, I often encountered that the terminal window opened too large in float mode the first time. I’m sure you know how to change this, even if I could do it, but I think it’s better to say something like this than to remain silent. By the way, your theme is amazing, it’s just an incredible feeling, thank you very much for your work!!

**Comment by flick0** [comment]
You'r welcome :>
And for the terminal, you should be able to change the resolution at the end of this line
https://github.com/flick0/dotfiles/blob/1cf107bcf29dea2f7c6c264e2766f035bf1fc998/theme.conf#L18

`~/.config/hypr/themes/yorha/theme.conf`
