### ISSUE TITLE
wallpaper and errors on dreamy

### ISSUE THREAD

**Issue by yocahu-lol** [flick0/dotfiles#66]
hey i just finished the install of the dreamy dot files yet i get no wallpaper on startup and keep having this red error strip on top of my desktop that keeps saying config error in file /home/yocahu/.config/hypr/hyprland.conf at line 31: config option <general:col.group_border> does not exist,  config error in file /home/yocahu/.config/hypr/hyprland.conf at line 32: config option <general:col.group_border_active> does not exist, config error in file /home/yocahu/.config/hypr/hyprland.conf at line 36: config option <decoration:blur_new_optimizations> does not exist, config error in file /home/yocahu/.config/hypr/hyprland.conf at line 43: config option <decoration:blur> does not exist, and config error in file /home/yocahu/.config/hypr/hyprland.conf at line 44: config option <decoration:blur_size> does not exist.

yet all of these exist on my config i am not sure what is going on any help would be most needed.

**Comment by Xag8031** [comment]
Hyprland changed the config rules and those rules that you're mentioning no longer work. I'd either comment them out, or look through the hyprland config documentation and attempt to rewrite the config.

**Comment by flick0** [comment]
updated hyprland.conf
ive been kinda busy with irl stuff so cant really keep up with hyprland's many breaking changes
