### ISSUE TITLE
error: target not found: light-git

### ISSUE THREAD

**Issue by ashtonbreadserk** [flick0/dotfiles#68]
Hi! I'm trying to install the dependancies however, light-git doesn't seem to be available?

**Comment by blankyblank** [comment]
is there any update on this? searching in the normal repos, and the aur I didn't see anything that light-git would possibly be.

**Comment by flick0** [comment]
i used `light` to control display backlight, light-git could be replace with the [non-git](https://aur.archlinux.org/packages/light) version

**Comment by flick0** [comment]
updated the readme
