### ISSUE TITLE
Screen Resolution Problem

### ISSUE THREAD

**Issue by ashtonbreadserk** [flick0/dotfiles#69]
My screen is 2560 x 1440 pixels. Is there any way how to fix the resolution on my screen?

![image](https://github.com/user-attachments/assets/6992cc93-67ae-416d-9ca4-bdb71c48818a)
![image](https://github.com/user-attachments/assets/4217d368-67d2-4f32-89af-07e67a732fad)

**Comment by flick0** [comment]
you can change scaling related stuff in this file https://github.com/flick0/dotfiles/blob/059b6af4c1ca83fa9916331ffaebb504e19938b0/components/ags/scaling.js#L3
