### ISSUE TITLE
Expand button

### ISSUE THREAD

**Issue by RedNekoderr** [flick0/dotfiles#7]
Hi! Can you please tell me how to add other components inside the "Expand" button?

**Comment by flick0** [comment]
you add an entry to [`.config/hypr/scripts/tools/expand`](https://github.com/flick0/dotfiles/blob/aurora/config/hypr/scripts/tools/expand), then you make a custom module on waybar referencing the `expand` script with the required args (eg:  `.config/hypr/scripts/tools/expand ss-icon` for the screenshot icon)

**Comment by Luks17** [comment]
Does this work only with custom modules? Or can I add an existing component, like the pulseaudio one, inside the expand button?
