### ISSUE TITLE
Player widget issue 

### ISSUE THREAD

**Issue by kitiwaii** [flick0/dotfiles#73]
When I try to log in after setting the Yorha theme, it throws me back to the login screen

**Comment by OohSorry** [comment]
It's because of new hyprland ver. (0.45.0). Variables have moved and you need to fix it in theme.conf.
https://wiki.hyprland.org/Configuring/Variables/#shadow
Here is example: 
![image](https://github.com/user-attachments/assets/c9e0c8fa-1722-4900-8e53-bb136ecce75b)

**Comment by kitiwaii** [comment]
When I do this, will the yorha theme be as shown? I'm not talking about the error.

**Comment by kitiwaii** [comment]
I was able to solve the problem but the theme is problematic and gives a font error in the terminal

Uploading 2024-12-05 12-43-03.mp4…

**Comment by kitiwaii** [comment]
I was able to solve the problem but the theme is problematic and gives a font error in the terminal

https://github.com/user-attachments/assets/b9983dda-625a-49da-9499-c8426cf8d319

**Comment by OohSorry** [comment]
> I was able to solve the problem but the theme is problematic and gives a font error in the terminal
> 
>  2024-12-05.12-43-03.mp4

Foot answered your question. There is no noto sans font used in this dotfiles (in this dotfiles only BlexMono Nerd Font)

**Comment by kitiwaii** [comment]
> > I was able to solve the problem but the theme is problematic and gives a font error in the terminal
> > 2024-12-05.12-43-03.mp4
> 
> Foot answered your question. There is no noto sans font used in this dotfiles (in this dotfiles only BlexMono Nerd Font)

I took care of everything thanks for your help

**Comment by OohSorry** [comment]
Do you installed imagemagick?

**Comment by kitiwaii** [comment]
> Did you install imagemagick?

I downloaded it but for some reason it didn't download

**Comment by kitiwaii** [comment]
> Did you install imagemagick?

I downloaded it but it still looks the same and when I type magick it gives an error at the bottom
![image](https://github.com/user-attachments/assets/c545a334-7c5d-4913-8b66-274bc2043302)

**Comment by kitiwaii** [comment]
![image](https://github.com/user-attachments/assets/8d372d10-65cb-4a7c-941c-d3df6e5574a0)
previously reinstalled the dot files and it got worse

**Comment by kitiwaii** [comment]
@OohSorry How can I download the old version of Hyprland?

**Comment by kitiwaii** [comment]
/tmp/bg.png ????

**Comment by kitiwaii** [comment]
I fixed it by re-putting the dot files
