### ISSUE TITLE
Can't adjust waybar height. 

### ISSUE THREAD

**Issue by EvilBoi123** [flick0/dotfiles#8]
Hello, i found your waybar to be pretty. But i have a problem to adjust waybar height. Perhaps you could point out which part i should adjust?

**Comment by flick0** [comment]
Ah, waybar height is a bit janky here,
Initially i used the height option from config but i cudnt get it to render shadows properly without cutting off anything and having the proper reserved space for hyprland, so i manage the margins thru css

To change the height u wud need to reduce all the `margin-bottom` or `margin-top`s in css

**Comment by EvilBoi123** [comment]
Thank you! It works now!
